In [1]:
import pandas as pd

In [3]:
df=pd.DataFrame({
    "name":['rajesh','pavan','sunil'],
    "age":[25,23,20]
})

In [4]:
print(df)

     name  age
0  rajesh   25
1   pavan   23
2   sunil   20

In [8]:
s=pd.Series([20,25,30])

In [9]:
print(s)

0    20
1    25
2    30
dtype: int64

In [ ]:
df=pd.read_csv("sales.csv")

In [ ]:
print(df)

           order_id  order_date product_id store_id customer_id  quantity  \
0       0RD00000001  2023-01-07      P0080     S093     C040749         5
1       0RD00000002  2023-10-22      P0173     S065     C020161         3
2       0RD00000003  2023-05-07      P0115     S078     C048069         2
3       0RD00000004  2024-06-23      P0186     S088     C047901         2
4       0RD00000005  2024-09-24      P0197     S054     C033950         1
...             ...         ...        ...      ...         ...       ...
999995  0RD00999996  2023-04-15      P0103     S053     C044763         4
999996  0RD00999997  2023-05-26      P0094     S058     C004441         2
999997  0RD00999998  2023-07-05      P0097     S041     C044879         3
999998  0RD00999999  2024-01-03      P0090     S083     C042525         1
999999  0RD01000000  2024-04-10      P0175     S090     C025078         1

        unit_price  discount  revenue   cost  profit
0            14.43      0.15    61.33  42.77   18.56
1            12.01      0.00    36.03  19.06   16.97
2            10.02      0.00    20.04  10.29    9.75
3            14.66      0.10    26.39  16.35   10.04
4            12.34      0.00    12.34   7.94    4.40
...            ...       ...      ...    ...     ...
999995        7.45      0.00    29.80  17.27   12.53
999996        6.09      0.00    12.18   7.81    4.37
999997        6.09      0.00    18.27  10.11    8.16
999998        4.90      0.00     4.90   2.56    2.34
999999        7.35      0.10     6.62   3.33    3.28

[1000000 rows x 11 columns]

In [ ]:
df.head()

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,10.04
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,4.40

In [ ]:
df.head(10)

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,10.04
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,4.40
5,0RD00000006,2024-03-29,P0160,S089,C008918,4,13.52,0.00,54.08,36.59,17.49
6,0RD00000007,2023-02-26,P0062,S024,C002897,1,11.97,0.10,10.77,7.16,3.61
7,0RD00000008,2023-11-03,P0111,S085,C038072,5,4.62,0.00,23.10,16.15,6.95
8,0RD00000009,2024-10-11,P0135,S029,C003786,4,7.88,0.00,31.52,19.90,11.62
9,0RD00000010,2023-12-17,P0069,S056,C043148,3,8.88,0.00,26.64,18.19,8.45

In [ ]:
df.describe()

,quantity,unit_price,discount,revenue,cost,profit
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,2.999589,9.002449,0.056248,25.486129,15.291554,10.194565
std,1.413621,3.462902,0.076809,16.367864,9.972706,6.778760
min,1.000000,3.000000,0.000000,2.400000,1.200000,0.730000
25%,2.000000,6.000000,0.000000,12.160000,7.240000,4.780000
50%,3.000000,9.010000,0.000000,21.920000,13.030000,8.600000
75%,4.000000,12.000000,0.150000,35.880000,21.410000,14.170000
max,5.000000,15.000000,0.200000,75.000000,52.430000,37.430000

In [ ]:
sales=pd.read_csv("sales.csv")

In [ ]:
print(sales)

           order_id  order_date product_id store_id customer_id  quantity  \
0       0RD00000001  2023-01-07      P0080     S093     C040749         5
1       0RD00000002  2023-10-22      P0173     S065     C020161         3
2       0RD00000003  2023-05-07      P0115     S078     C048069         2
3       0RD00000004  2024-06-23      P0186     S088     C047901         2
4       0RD00000005  2024-09-24      P0197     S054     C033950         1
...             ...         ...        ...      ...         ...       ...
999995  0RD00999996  2023-04-15      P0103     S053     C044763         4
999996  0RD00999997  2023-05-26      P0094     S058     C004441         2
999997  0RD00999998  2023-07-05      P0097     S041     C044879         3
999998  0RD00999999  2024-01-03      P0090     S083     C042525         1
999999  0RD01000000  2024-04-10      P0175     S090     C025078         1

        unit_price  discount  revenue   cost  profit
0            14.43      0.15    61.33  42.77   18.56
1            12.01      0.00    36.03  19.06   16.97
2            10.02      0.00    20.04  10.29    9.75
3            14.66      0.10    26.39  16.35   10.04
4            12.34      0.00    12.34   7.94    4.40
...            ...       ...      ...    ...     ...
999995        7.45      0.00    29.80  17.27   12.53
999996        6.09      0.00    12.18   7.81    4.37
999997        6.09      0.00    18.27  10.11    8.16
999998        4.90      0.00     4.90   2.56    2.34
999999        7.35      0.10     6.62   3.33    3.28

[1000000 rows x 11 columns]

In [ ]:
stores=pd.read_csv("stores.csv")

In [ ]:
print(stores)

   store_id           store_name       city    country store_type
0      S001    Chocolate Store 1   New York     Canada     Retail
1      S002    Chocolate Store 2  Melbourne     Canada       Mall
2      S003    Chocolate Store 3     Berlin     France       Mall
3      S004    Chocolate Store 4      Paris         UK    Airport
4      S005    Chocolate Store 5     Sydney        USA     Online
..      ...                  ...        ...        ...        ...
95     S096   Chocolate Store 96     Berlin         UK       Mall
96     S097   Chocolate Store 97    Toronto     Canada       Mall
97     S098   Chocolate Store 98   New York  Australia     Online
98     S099   Chocolate Store 99    Toronto  Australia       Mall
99     S100  Chocolate Store 100     Berlin     France    Airport

[100 rows x 5 columns]

In [ ]:
ms=pd.merge(sales,stores,on="store_id")

In [ ]:
print(ms)

           order_id  order_date product_id store_id customer_id  quantity  \
0       0RD00000001  2023-01-07      P0080     S093     C040749         5
1       0RD00000002  2023-10-22      P0173     S065     C020161         3
2       0RD00000003  2023-05-07      P0115     S078     C048069         2
3       0RD00000004  2024-06-23      P0186     S088     C047901         2
4       0RD00000005  2024-09-24      P0197     S054     C033950         1
...             ...         ...        ...      ...         ...       ...
999995  0RD00999996  2023-04-15      P0103     S053     C044763         4
999996  0RD00999997  2023-05-26      P0094     S058     C004441         2
999997  0RD00999998  2023-07-05      P0097     S041     C044879         3
999998  0RD00999999  2024-01-03      P0090     S083     C042525         1
999999  0RD01000000  2024-04-10      P0175     S090     C025078         1

        unit_price  discount  revenue   cost  profit          store_name  \
0            14.43      0.15    61.33  42.77   18.56  Chocolate Store 93
1            12.01      0.00    36.03  19.06   16.97  Chocolate Store 65
2            10.02      0.00    20.04  10.29    9.75  Chocolate Store 78
3            14.66      0.10    26.39  16.35   10.04  Chocolate Store 88
4            12.34      0.00    12.34   7.94    4.40  Chocolate Store 54
...            ...       ...      ...    ...     ...                 ...
999995        7.45      0.00    29.80  17.27   12.53  Chocolate Store 53
999996        6.09      0.00    12.18   7.81    4.37  Chocolate Store 58
999997        6.09      0.00    18.27  10.11    8.16  Chocolate Store 41
999998        4.90      0.00     4.90   2.56    2.34  Chocolate Store 83
999999        7.35      0.10     6.62   3.33    3.28  Chocolate Store 90

            city    country store_type
0         Sydney         UK    Airport
1       New York  Australia     Retail
2         London         UK    Airport
3        Toronto        USA     Retail
4         London     Canada     Online
...          ...        ...        ...
999995  New York        USA     Retail
999996     Paris        USA    Airport
999997    London    Germany    Airport
999998   Toronto     France       Mall
999999   Toronto     France     Online

[1000000 rows x 15 columns]

In [ ]:
ms.head()

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit,store_name,city,country,store_type
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56,Chocolate Store 93,Sydney,UK,Airport
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97,Chocolate Store 65,New York,Australia,Retail
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75,Chocolate Store 78,London,UK,Airport
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,10.04,Chocolate Store 88,Toronto,USA,Retail
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,4.40,Chocolate Store 54,London,Canada,Online

In [ ]:
ms.tail()

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit,store_name,city,country,store_type
999995,0RD00999996,2023-04-15,P0103,S053,C044763,4,7.45,0.0,29.80,17.27,12.53,Chocolate Store 53,New York,USA,Retail
999996,0RD00999997,2023-05-26,P0094,S058,C004441,2,6.09,0.0,12.18,7.81,4.37,Chocolate Store 58,Paris,USA,Airport
999997,0RD00999998,2023-07-05,P0097,S041,C044879,3,6.09,0.0,18.27,10.11,8.16,Chocolate Store 41,London,Germany,Airport
999998,0RD00999999,2024-01-03,P0090,S083,C042525,1,4.90,0.0,4.90,2.56,2.34,Chocolate Store 83,Toronto,France,Mall
999999,0RD01000000,2024-04-10,P0175,S090,C025078,1,7.35,0.1,6.62,3.33,3.28,Chocolate Store 90,Toronto,France,Online

In [ ]:
customer=pd.read_csv("customers.csv")

In [ ]:
print(customer)

      customer_id  age  gender  loyalty_member   join_date
0         C000001   40    Male               1  2025-05-21
1         C000002   47    Male               0  2021-12-26
2         C000003   58  Female               1  2022-09-13
3         C000004   25  Female               0  2025-02-27
4         C000005   43    Male               0  2023-08-31
...           ...  ...     ...             ...         ...
49995     C049996   30  Female               1  2022-11-21
49996     C049997   24  Female               0  2022-08-30
49997     C049998   53    Male               0  2024-09-22
49998     C049999   31  Female               1  2025-08-23
49999     C050000   39  Female               1  2023-12-02

[50000 rows x 5 columns]

In [ ]:
print(customer["age"])

0        40
1        47
2        58
3        25
4        43
         ..
49995    30
49996    24
49997    53
49998    31
49999    39
Name: age, Length: 50000, dtype: int64

In [ ]:
print(customer[['age','gender']])

       age  gender
0       40    Male
1       47    Male
2       58  Female
3       25  Female
4       43    Male
...    ...     ...
49995   30  Female
49996   24  Female
49997   53    Male
49998   31  Female
49999   39  Female

[50000 rows x 2 columns]

In [ ]:
customer.describe()

                age  loyalty_member
count  50000.000000    50000.000000
mean      44.026100        0.502080
std       15.328333        0.500001
min       18.000000        0.000000
25%       31.000000        0.000000
50%       44.000000        1.000000
75%       57.000000        1.000000
max       70.000000        1.000000

In [ ]:
print(customer.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     50000 non-null  object
 1   age             50000 non-null  int64
 2   gender          50000 non-null  object
 3   loyalty_member  50000 non-null  int64
 4   join_date       50000 non-null  object
dtypes: int64(2), object(3)
memory usage: 1.9+ MB
None

In [ ]:
print(customer.loc[0])

customer_id          C000001
age                       40
gender                  Male
loyalty_member             1
join_date         2025-05-21
Name: 0, dtype: object

In [ ]:
print(customer[customer['age']>40])

      customer_id  age  gender  loyalty_member   join_date
1         C000002   47    Male               0  2021-12-26
2         C000003   58  Female               1  2022-09-13
4         C000005   43    Male               0  2023-08-31
6         C000007   51    Male               1  2024-07-28
7         C000008   56  Female               0  2024-08-12
...           ...  ...     ...             ...         ...
49989     C049990   63    Male               1  2024-04-06
49990     C049991   56    Male               1  2023-12-16
49992     C049993   47    Male               0  2021-05-25
49994     C049995   70    Male               0  2023-08-03
49997     C049998   53    Male               0  2024-09-22

[28294 rows x 5 columns]

In [ ]:
print(customer.isnull())

       customer_id    age  gender  loyalty_member  join_date
0            False  False   False           False      False
1            False  False   False           False      False
2            False  False   False           False      False
3            False  False   False           False      False
4            False  False   False           False      False
...            ...    ...     ...             ...        ...
49995        False  False   False           False      False
49996        False  False   False           False      False
49997        False  False   False           False      False
49998        False  False   False           False      False
49999        False  False   False           False      False

[50000 rows x 5 columns]

In [ ]:
products=pd.read_csv("products.csv")

In [ ]:
print(products)

    product_id           product_name    brand category  cocoa_percent  \
0        P0001    White Chocolate 80%     Mars  Truffle             80
1        P0002     Dark Chocolate 70%  Cadbury  Praline             70
2        P0003  Truffle Chocolate 70%  Hershey  Praline             70
3        P0004     Milk Chocolate 50%     Mars  Praline             50
4        P0005    White Chocolate 70%  Ferrero    White             70
..         ...                    ...      ...      ...            ...
195      P0196    White Chocolate 60%     Mars  Praline             60
196      P0197  Truffle Chocolate 90%  Hershey  Truffle             90
197      P0198     Dark Chocolate 90%  Ferrero    White             90
198      P0199     Dark Chocolate 70%  Hershey    White             70
199      P0200     Milk Chocolate 50%  Cadbury     Milk             50

     weight_g
0         120
1         100
2         120
3          80
4          50
..        ...
195        80
196       120
197        80
198        80
199       100

[200 rows x 6 columns]

In [ ]:
ms1=pd.merge(products,sales,on="product_id")

In [ ]:
print(ms1)

       product_id         product_name    brand category  cocoa_percent  \
0           P0001  White Chocolate 80%     Mars  Truffle             80
1           P0001  White Chocolate 80%     Mars  Truffle             80
2           P0001  White Chocolate 80%     Mars  Truffle             80
3           P0001  White Chocolate 80%     Mars  Truffle             80
4           P0001  White Chocolate 80%     Mars  Truffle             80
...           ...                  ...      ...      ...            ...
990231      P0200   Milk Chocolate 50%  Cadbury     Milk             50
990232      P0200   Milk Chocolate 50%  Cadbury     Milk             50
990233      P0200   Milk Chocolate 50%  Cadbury     Milk             50
990234      P0200   Milk Chocolate 50%  Cadbury     Milk             50
990235      P0200   Milk Chocolate 50%  Cadbury     Milk             50

        weight_g     order_id  order_date store_id customer_id  quantity  \
0            120  0RD00000046  2023-08-23     S091     C033225         5
1            120  0RD00000168  2024-11-25     S084     C036726         4
2            120  0RD00000263  2024-08-24     S099     C030501         4
3            120  0RD00000572  2024-10-30     S068     C039667         5
4            120  0RD00000704  2024-08-30     S083     C026518         1
...          ...          ...         ...      ...         ...       ...
990231       100  0RD00998502  2023-04-01     S078     C001957         3
990232       100  0RD00998524  2024-09-24     S081     C045447         2
990233       100  0RD00998530  2023-05-20     S002     C042574         2
990234       100  0RD00998839  2023-08-21     S088     C038365         3
990235       100  0RD00999324  2024-10-10     S013     C011507         4

        unit_price  discount  revenue   cost  profit
0             6.00       0.0    30.00  16.71   13.29
1            11.94       0.0    47.76  26.86   20.90
2             6.73       0.0    26.92  14.34   12.58
3            11.13       0.0    55.65  28.40   27.25
4            10.34       0.2     8.27   4.42    3.85
...            ...       ...      ...    ...     ...
990231        5.80       0.0    17.40  10.82    6.58
990232        6.83       0.0    13.66   7.96    5.70
990233       14.19       0.0    28.38  17.95   10.43
990234       14.86       0.0    44.58  24.71   19.87
990235        9.50       0.0    38.00  19.64   18.36

[990236 rows x 16 columns]

In [ ]:
ms1.sample(3)

,product_id,product_name,brand,category,cocoa_percent,weight_g,order_id,order_date,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit
960409,P0194,Truffle Chocolate 90%,Godiva,Milk,90,200,0RD00963198,2024-07-14,S095,C044050,4,11.49,0.0,45.96,25.34,20.62
100559,P0021,Dark Chocolate 50%,Cadbury,White,50,50,0RD00241471,2023-01-07,S054,C011066,5,14.32,0.0,71.60,41.60,30.00
369032,P0075,Praline Chocolate 70%,Godiva,White,70,200,0RD00599605,2023-11-12,S078,C004379,3,13.70,0.0,41.10,26.41,14.69

In [ ]:
ms1.dtypes

product_id        object
product_name      object
brand             object
category          object
cocoa_percent      int64
weight_g           int64
order_id          object
order_date        object
store_id          object
customer_id       object
quantity           int64
unit_price       float64
discount         float64
revenue          float64
cost             float64
profit           float64
dtype: object

In [ ]:
ms1.columns

Index(['product_id', 'product_name', 'brand', 'category', 'cocoa_percent',
       'weight_g', 'order_id', 'order_date', 'store_id', 'customer_id',
       'quantity', 'unit_price', 'discount', 'revenue', 'cost', 'profit'],
      dtype='object')

In [ ]:
ms1.iloc[0]

product_id                     P0001
product_name     White Chocolate 80%
brand                           Mars
category                     Truffle
cocoa_percent                     80
weight_g                         120
order_id                 0RD00000046
order_date                2023-08-23
store_id                        S091
customer_id                  C033225
quantity                           5
unit_price                       6.0
discount                         0.0
revenue                         30.0
cost                           16.71
profit                         13.29
Name: 0, dtype: object

In [ ]:
ms1[ms1['category']=='Dark']

,product_id,product_name,brand,category,cocoa_percent,weight_g,order_id,order_date,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit
24847,P0006,Milk Chocolate 50%,Hershey,Dark,50,50,0RD00000088,2023-12-10,S005,C024721,3,9.96,0.10,26.89,15.88,11.01
24848,P0006,Milk Chocolate 50%,Hershey,Dark,50,50,0RD00000129,2024-06-11,S034,C033593,5,12.54,0.15,53.29,35.35,17.95
24849,P0006,Milk Chocolate 50%,Hershey,Dark,50,50,0RD00000329,2023-03-11,S034,C011601,4,8.72,0.00,34.88,19.28,15.60
24850,P0006,Milk Chocolate 50%,Hershey,Dark,50,50,0RD00000419,2023-05-25,S025,C030585,1,8.65,0.20,6.92,4.49,2.43
24851,P0006,Milk Chocolate 50%,Hershey,Dark,50,50,0RD00000465,2023-03-19,S033,C021068,5,3.86,0.00,19.30,9.71,9.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965575,P0195,White Chocolate 90%,Cadbury,Dark,90,120,0RD00999113,2024-07-10,S009,C016537,2,10.71,0.10,19.28,13.33,5.95
965576,P0195,White Chocolate 90%,Cadbury,Dark,90,120,0RD00999416,2024-09-26,S028,C014006,2,12.73,0.00,25.46,16.18,9.28
965577,P0195,White Chocolate 90%,Cadbury,Dark,90,120,0RD00999497,2024-03-01,S036,C021153,4,10.23,0.20,32.74,21.29,11.45
965578,P0195,White Chocolate 90%,Cadbury,Dark,90,120,0RD00999558,2024-02-24,S040,C025614,2,5.84,0.00,11.68,8.04,3.64
965579,P0195,White Chocolate 90%,Cadbury,Dark,90,120,0RD00999741,2024-03-23,S092,C022906,3,13.82,0.15,35.24,22.12,13.12

In [ ]:
ms1.groupby('product_name')['profit'].mean()

product_name
Dark Chocolate 50%       10.193791
Dark Chocolate 60%       10.217344
Dark Chocolate 70%       10.245325
Dark Chocolate 80%       10.236577
Dark Chocolate 90%       10.147882
Milk Chocolate 50%       10.231516
Milk Chocolate 60%       10.252002
Milk Chocolate 70%       10.227364
Milk Chocolate 80%       10.181358
Milk Chocolate 90%       10.179706
Praline Chocolate 50%    10.232501
Praline Chocolate 60%    10.178415
Praline Chocolate 70%    10.163235
Praline Chocolate 80%    10.164448
Praline Chocolate 90%    10.218315
Truffle Chocolate 50%    10.161854
Truffle Chocolate 60%    10.206109
Truffle Chocolate 70%    10.199804
Truffle Chocolate 80%    10.183931
Truffle Chocolate 90%    10.136764
White Chocolate 50%      10.195860
White Chocolate 60%      10.167651
White Chocolate 70%      10.151090
White Chocolate 80%      10.208192
White Chocolate 90%      10.181978
Name: profit, dtype: float64

In [ ]:
print(ms1)

       product_id         product_name    brand category  cocoa_percent  \
0           P0001  White Chocolate 80%     Mars  Truffle             80
1           P0001  White Chocolate 80%     Mars  Truffle             80
2           P0001  White Chocolate 80%     Mars  Truffle             80
3           P0001  White Chocolate 80%     Mars  Truffle             80
4           P0001  White Chocolate 80%     Mars  Truffle             80
...           ...                  ...      ...      ...            ...
990231      P0200   Milk Chocolate 50%  Cadbury     Milk             50
990232      P0200   Milk Chocolate 50%  Cadbury     Milk             50
990233      P0200   Milk Chocolate 50%  Cadbury     Milk             50
990234      P0200   Milk Chocolate 50%  Cadbury     Milk             50
990235      P0200   Milk Chocolate 50%  Cadbury     Milk             50

        weight_g     order_id  order_date store_id customer_id  quantity  \
0            120  0RD00000046  2023-08-23     S091     C033225         5
1            120  0RD00000168  2024-11-25     S084     C036726         4
2            120  0RD00000263  2024-08-24     S099     C030501         4
3            120  0RD00000572  2024-10-30     S068     C039667         5
4            120  0RD00000704  2024-08-30     S083     C026518         1
...          ...          ...         ...      ...         ...       ...
990231       100  0RD00998502  2023-04-01     S078     C001957         3
990232       100  0RD00998524  2024-09-24     S081     C045447         2
990233       100  0RD00998530  2023-05-20     S002     C042574         2
990234       100  0RD00998839  2023-08-21     S088     C038365         3
990235       100  0RD00999324  2024-10-10     S013     C011507         4

        unit_price  discount  revenue   cost  profit
0             6.00       0.0    30.00  16.71   13.29
1            11.94       0.0    47.76  26.86   20.90
2             6.73       0.0    26.92  14.34   12.58
3            11.13       0.0    55.65  28.40   27.25
4            10.34       0.2     8.27   4.42    3.85
...            ...       ...      ...    ...     ...
990231        5.80       0.0    17.40  10.82    6.58
990232        6.83       0.0    13.66   7.96    5.70
990233       14.19       0.0    28.38  17.95   10.43
990234       14.86       0.0    44.58  24.71   19.87
990235        9.50       0.0    38.00  19.64   18.36

[990236 rows x 16 columns]

In [ ]:
ms1['product_id'].value_counts()

product_id
P0021    5141
P0091    5132
P0107    5115
P0008    5092
P0146    5089
         ...
P0080    4808
P0178    4797
P0028    4761
P0035    4758
P0048    4744
Name: count, Length: 200, dtype: int64

In [ ]:
pd.concat([ms,ms1])

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit,store_name,city,country,store_type,product_name,brand,category,cocoa_percent,weight_g
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56,Chocolate Store 93,Sydney,UK,Airport,NaN,NaN,NaN,NaN,NaN
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97,Chocolate Store 65,New York,Australia,Retail,NaN,NaN,NaN,NaN,NaN
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75,Chocolate Store 78,London,UK,Airport,NaN,NaN,NaN,NaN,NaN
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,10.04,Chocolate Store 88,Toronto,USA,Retail,NaN,NaN,NaN,NaN,NaN
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,4.40,Chocolate Store 54,London,Canada,Online,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990231,0RD00998502,2023-04-01,P0200,S078,C001957,3,5.80,0.00,17.40,10.82,6.58,NaN,NaN,NaN,NaN,Milk Chocolate 50%,Cadbury,Milk,50.0,100.0
990232,0RD00998524,2024-09-24,P0200,S081,C045447,2,6.83,0.00,13.66,7.96,5.70,NaN,NaN,NaN,NaN,Milk Chocolate 50%,Cadbury,Milk,50.0,100.0
990233,0RD00998530,2023-05-20,P0200,S002,C042574,2,14.19,0.00,28.38,17.95,10.43,NaN,NaN,NaN,NaN,Milk Chocolate 50%,Cadbury,Milk,50.0,100.0
990234,0RD00998839,2023-08-21,P0200,S088,C038365,3,14.86,0.00,44.58,24.71,19.87,NaN,NaN,NaN,NaN,Milk Chocolate 50%,Cadbury,Milk,50.0,100.0
990235,0RD00999324,2024-10-10,P0200,S013,C011507,4,9.50,0.00,38.00,19.64,18.36,NaN,NaN,NaN,NaN,Milk Chocolate 50%,Cadbury,Milk,50.0,100.0

In [ ]:
ms1.shape

(990236, 16)

In [ ]:
ms1['profit'].sum()

np.float64(10095641.909999995)