In [ ]:
import pandas as pd

In [ ]:
pd.read_csv("products.csv")

,product_id,product_name,brand,category,cocoa_percent,weight_g
0,P0001,White Chocolate 80%,Mars,Truffle,80,120
1,P0002,Dark Chocolate 70%,Cadbury,Praline,70,100
2,P0003,Truffle Chocolate 70%,Hershey,Praline,70,120
3,P0004,Milk Chocolate 50%,Mars,Praline,50,80
4,P0005,White Chocolate 70%,Ferrero,White,70,50
...,...,...,...,...,...,...
195,P0196,White Chocolate 60%,Mars,Praline,60,80
196,P0197,Truffle Chocolate 90%,Hershey,Truffle,90,120
197,P0198,Dark Chocolate 90%,Ferrero,White,90,80
198,P0199,Dark Chocolate 70%,Hershey,White,70,80
199,P0200,Milk Chocolate 50%,Cadbury,Milk,50,100

In [ ]:
products=pd.read_csv("products.csv")

In [ ]:
print(products)

    product_id           product_name    brand category  cocoa_percent  \
0        P0001    White Chocolate 80%     Mars  Truffle             80
1        P0002     Dark Chocolate 70%  Cadbury  Praline             70
2        P0003  Truffle Chocolate 70%  Hershey  Praline             70
3        P0004     Milk Chocolate 50%     Mars  Praline             50
4        P0005    White Chocolate 70%  Ferrero    White             70
..         ...                    ...      ...      ...            ...
195      P0196    White Chocolate 60%     Mars  Praline             60
196      P0197  Truffle Chocolate 90%  Hershey  Truffle             90
197      P0198     Dark Chocolate 90%  Ferrero    White             90
198      P0199     Dark Chocolate 70%  Hershey    White             70
199      P0200     Milk Chocolate 50%  Cadbury     Milk             50

     weight_g
0         120
1         100
2         120
3          80
4          50
..        ...
195        80
196       120
197        80
198        80
199       100

[200 rows x 6 columns]

# New Section

In [ ]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     200 non-null    object
 1   product_name   200 non-null    object
 2   brand          200 non-null    object
 3   category       200 non-null    object
 4   cocoa_percent  200 non-null    int64
 5   weight_g       200 non-null    int64
dtypes: int64(2), object(4)
memory usage: 9.5+ KB

In [ ]:
products.describe()

       cocoa_percent    weight_g
count     200.000000  200.000000
mean       69.150000  107.500000
std        14.623499   50.898954
min        50.000000   50.000000
25%        50.000000   80.000000
50%        70.000000  100.000000
75%        80.000000  120.000000
max        90.000000  200.000000

In [ ]:
products.shape

(200, 6)

In [ ]:
products.size

1200

In [ ]:
products.columns

Index(['product_id', 'product_name', 'brand', 'category', 'cocoa_percent',
       'weight_g'],
      dtype='object')

In [ ]:
products.index

RangeIndex(start=0, stop=200, step=1)

In [ ]:
products.dtypes

product_id       object
product_name     object
brand            object
category         object
cocoa_percent     int64
weight_g          int64
dtype: object

In [ ]:
products['product_name']

0        White Chocolate 80%
1         Dark Chocolate 70%
2      Truffle Chocolate 70%
3         Milk Chocolate 50%
4        White Chocolate 70%
               ...
195      White Chocolate 60%
196    Truffle Chocolate 90%
197       Dark Chocolate 90%
198       Dark Chocolate 70%
199       Milk Chocolate 50%
Name: product_name, Length: 200, dtype: object

In [ ]:
products[["product_name","brand"]]

              product_name    brand
0      White Chocolate 80%     Mars
1       Dark Chocolate 70%  Cadbury
2    Truffle Chocolate 70%  Hershey
3       Milk Chocolate 50%     Mars
4      White Chocolate 70%  Ferrero
..                     ...      ...
195    White Chocolate 60%     Mars
196  Truffle Chocolate 90%  Hershey
197     Dark Chocolate 90%  Ferrero
198     Dark Chocolate 70%  Hershey
199     Milk Chocolate 50%  Cadbury

[200 rows x 2 columns]

Select a single row by label:

In [ ]:
products.loc[0]

product_id                     P0001
product_name     White Chocolate 80%
brand                           Mars
category                     Truffle
cocoa_percent                     80
weight_g                         120
Name: 0, dtype: object

Select specific rows and columns:

In [ ]:
products.loc[0,"brand"]

'Mars'

In [ ]:
products.loc[[0,1],'brand']

0       Mars
1    Cadbury
Name: brand, dtype: object

In [ ]:
products.loc['product_name':'brand','category']

Series([], Name: category, dtype: object)

In [ ]:
products.iloc[0,1]

'White Chocolate 80%'

row labe + column name

In [ ]:
products.at[0,'brand']

'Mars'

In [ ]:
products.iat[1,1]

'Dark Chocolate 70%'

In [ ]:
products[products['cocoa_percent']>50]

,product_id,product_name,brand,category,cocoa_percent,weight_g
0,P0001,White Chocolate 80%,Mars,Truffle,80,120
1,P0002,Dark Chocolate 70%,Cadbury,Praline,70,100
2,P0003,Truffle Chocolate 70%,Hershey,Praline,70,120
4,P0005,White Chocolate 70%,Ferrero,White,70,50
6,P0007,Praline Chocolate 70%,Cadbury,Praline,70,120
...,...,...,...,...,...,...
194,P0195,White Chocolate 90%,Cadbury,Dark,90,120
195,P0196,White Chocolate 60%,Mars,Praline,60,80
196,P0197,Truffle Chocolate 90%,Hershey,Truffle,90,120
197,P0198,Dark Chocolate 90%,Ferrero,White,90,80
198,P0199,Dark Chocolate 70%,Hershey,White,70,80

In [ ]:
products.isnull()

     product_id  product_name  brand  category  cocoa_percent  weight_g
0         False         False  False     False          False     False
1         False         False  False     False          False     False
2         False         False  False     False          False     False
3         False         False  False     False          False     False
4         False         False  False     False          False     False
..          ...           ...    ...       ...            ...       ...
195       False         False  False     False          False     False
196       False         False  False     False          False     False
197       False         False  False     False          False     False
198       False         False  False     False          False     False
199       False         False  False     False          False     False

[200 rows x 6 columns]

In [ ]:
products.fillna(0)

,product_id,product_name,brand,category,cocoa_percent,weight_g
0,P0001,White Chocolate 80%,Mars,Truffle,80,120
1,P0002,Dark Chocolate 70%,Cadbury,Praline,70,100
2,P0003,Truffle Chocolate 70%,Hershey,Praline,70,120
3,P0004,Milk Chocolate 50%,Mars,Praline,50,80
4,P0005,White Chocolate 70%,Ferrero,White,70,50
...,...,...,...,...,...,...
195,P0196,White Chocolate 60%,Mars,Praline,60,80
196,P0197,Truffle Chocolate 90%,Hershey,Truffle,90,120
197,P0198,Dark Chocolate 90%,Ferrero,White,90,80
198,P0199,Dark Chocolate 70%,Hershey,White,70,80
199,P0200,Milk Chocolate 50%,Cadbury,Milk,50,100

In [ ]:
products.dropna()

,product_id,product_name,brand,category,cocoa_percent,weight_g
0,P0001,White Chocolate 80%,Mars,Truffle,80,120
1,P0002,Dark Chocolate 70%,Cadbury,Praline,70,100
2,P0003,Truffle Chocolate 70%,Hershey,Praline,70,120
3,P0004,Milk Chocolate 50%,Mars,Praline,50,80
4,P0005,White Chocolate 70%,Ferrero,White,70,50
...,...,...,...,...,...,...
195,P0196,White Chocolate 60%,Mars,Praline,60,80
196,P0197,Truffle Chocolate 90%,Hershey,Truffle,90,120
197,P0198,Dark Chocolate 90%,Ferrero,White,90,80
198,P0199,Dark Chocolate 70%,Hershey,White,70,80
199,P0200,Milk Chocolate 50%,Cadbury,Milk,50,100

In [ ]:
products.isnull()

     product_id  product_name  brand  category  cocoa_percent  weight_g
0         False         False  False     False          False     False
1         False         False  False     False          False     False
2         False         False  False     False          False     False
3         False         False  False     False          False     False
4         False         False  False     False          False     False
..          ...           ...    ...       ...            ...       ...
195       False         False  False     False          False     False
196       False         False  False     False          False     False
197       False         False  False     False          False     False
198       False         False  False     False          False     False
199       False         False  False     False          False     False

[200 rows x 6 columns]

In [ ]:
products.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Length: 200, dtype: bool

In [ ]:
products.drop_duplicates()

,product_id,product_name,brand,category,cocoa_percent,weight_g
0,P0001,White Chocolate 80%,Mars,Truffle,80,120
1,P0002,Dark Chocolate 70%,Cadbury,Praline,70,100
2,P0003,Truffle Chocolate 70%,Hershey,Praline,70,120
3,P0004,Milk Chocolate 50%,Mars,Praline,50,80
4,P0005,White Chocolate 70%,Ferrero,White,70,50
...,...,...,...,...,...,...
195,P0196,White Chocolate 60%,Mars,Praline,60,80
196,P0197,Truffle Chocolate 90%,Hershey,Truffle,90,120
197,P0198,Dark Chocolate 90%,Ferrero,White,90,80
198,P0199,Dark Chocolate 70%,Hershey,White,70,80
199,P0200,Milk Chocolate 50%,Cadbury,Milk,50,100

In [ ]:
products['product_id'].value_counts()

product_id
P0001    1
P0002    1
P0003    1
P0004    1
P0005    1
        ..
P0196    1
P0197    1
P0198    1
P0199    1
P0200    1
Name: count, Length: 200, dtype: int64

In [ ]:
products['brand'].str.upper()

0         MARS
1      CADBURY
2      HERSHEY
3         MARS
4      FERRERO
        ...
195       MARS
196    HERSHEY
197    FERRERO
198    HERSHEY
199    CADBURY
Name: brand, Length: 200, dtype: object

In [ ]:
sales=pd.read_csv("sales.csv")

In [ ]:
print(sales)

           order_id  order_date product_id store_id customer_id  quantity  \
0       0RD00000001  2023-01-07      P0080     S093     C040749         5
1       0RD00000002  2023-10-22      P0173     S065     C020161         3
2       0RD00000003  2023-05-07      P0115     S078     C048069         2
3       0RD00000004  2024-06-23      P0186     S088     C047901         2
4       0RD00000005  2024-09-24      P0197     S054     C033950         1
...             ...         ...        ...      ...         ...       ...
999995  0RD00999996  2023-04-15      P0103     S053     C044763         4
999996  0RD00999997  2023-05-26      P0094     S058     C004441         2
999997  0RD00999998  2023-07-05      P0097     S041     C044879         3
999998  0RD00999999  2024-01-03      P0090     S083     C042525         1
999999  0RD01000000  2024-04-10      P0175     S090     C025078         1

        unit_price  discount  revenue   cost  profit
0            14.43      0.15    61.33  42.77   18.56
1            12.01      0.00    36.03  19.06   16.97
2            10.02      0.00    20.04  10.29    9.75
3            14.66      0.10    26.39  16.35   10.04
4            12.34      0.00    12.34   7.94    4.40
...            ...       ...      ...    ...     ...
999995        7.45      0.00    29.80  17.27   12.53
999996        6.09      0.00    12.18   7.81    4.37
999997        6.09      0.00    18.27  10.11    8.16
999998        4.90      0.00     4.90   2.56    2.34
999999        7.35      0.10     6.62   3.33    3.28

[1000000 rows x 11 columns]

In [ ]:
sales.isnull()

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
999995,False,False,False,False,False,False,False,False,False,False,False
999996,False,False,False,False,False,False,False,False,False,False,False
999997,False,False,False,False,False,False,False,False,False,False,False
999998,False,False,False,False,False,False,False,False,False,False,False
999999,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
sales.isnull().sum()

order_id       0
order_date     0
product_id     0
store_id       0
customer_id    0
quantity       0
unit_price     0
discount       0
revenue        0
cost           0
profit         0
dtype: int64

In [ ]:
sales.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
999995    False
999996    False
999997    False
999998    False
999999    False
Length: 1000000, dtype: bool

In [ ]:
sales.drop_duplicates()

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,10.04
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,4.40
...,...,...,...,...,...,...,...,...,...,...,...
999995,0RD00999996,2023-04-15,P0103,S053,C044763,4,7.45,0.00,29.80,17.27,12.53
999996,0RD00999997,2023-05-26,P0094,S058,C004441,2,6.09,0.00,12.18,7.81,4.37
999997,0RD00999998,2023-07-05,P0097,S041,C044879,3,6.09,0.00,18.27,10.11,8.16
999998,0RD00999999,2024-01-03,P0090,S083,C042525,1,4.90,0.00,4.90,2.56,2.34
999999,0RD01000000,2024-04-10,P0175,S090,C025078,1,7.35,0.10,6.62,3.33,3.28

In [ ]:
sales.groupby("discount")['unit_price'].sum()

discount
0.00    5627888.99
0.10    1122414.71
0.15    1129441.33
0.20    1122704.01
Name: unit_price, dtype: float64

In [ ]:
customers=pd.read_csv("customers.csv")

In [ ]:
customers.groupby("age")

In [ ]:
print(sales)

           order_id  order_date product_id store_id customer_id  quantity  \
0       0RD00000001  2023-01-07      P0080     S093     C040749         5
1       0RD00000002  2023-10-22      P0173     S065     C020161         3
2       0RD00000003  2023-05-07      P0115     S078     C048069         2
3       0RD00000004  2024-06-23      P0186     S088     C047901         2
4       0RD00000005  2024-09-24      P0197     S054     C033950         1
...             ...         ...        ...      ...         ...       ...
999995  0RD00999996  2023-04-15      P0103     S053     C044763         4
999996  0RD00999997  2023-05-26      P0094     S058     C004441         2
999997  0RD00999998  2023-07-05      P0097     S041     C044879         3
999998  0RD00999999  2024-01-03      P0090     S083     C042525         1
999999  0RD01000000  2024-04-10      P0175     S090     C025078         1

        unit_price  discount  revenue   cost  profit
0            14.43      0.15    61.33  42.77   18.56
1            12.01      0.00    36.03  19.06   16.97
2            10.02      0.00    20.04  10.29    9.75
3            14.66      0.10    26.39  16.35   10.04
4            12.34      0.00    12.34   7.94    4.40
...            ...       ...      ...    ...     ...
999995        7.45      0.00    29.80  17.27   12.53
999996        6.09      0.00    12.18   7.81    4.37
999997        6.09      0.00    18.27  10.11    8.16
999998        4.90      0.00     4.90   2.56    2.34
999999        7.35      0.10     6.62   3.33    3.28

[1000000 rows x 11 columns]

In [ ]:
mcsa=pd.merge(customers,sales,on='customer_id')

In [ ]:
print(mcsa)

       customer_id  age  gender  loyalty_member   join_date     order_id  \
0          C000001   40    Male               1  2025-05-21  0RD00007338
1          C000001   40    Male               1  2025-05-21  0RD00065169
2          C000001   40    Male               1  2025-05-21  0RD00070369
3          C000001   40    Male               1  2025-05-21  0RD00085016
4          C000001   40    Male               1  2025-05-21  0RD00169882
...            ...  ...     ...             ...         ...          ...
999995     C050000   39  Female               1  2023-12-02  0RD00805872
999996     C050000   39  Female               1  2023-12-02  0RD00890383
999997     C050000   39  Female               1  2023-12-02  0RD00940128
999998     C050000   39  Female               1  2023-12-02  0RD00966042
999999     C050000   39  Female               1  2023-12-02  0RD00989486

        order_date product_id store_id  quantity  unit_price  discount  \
0       2023-10-06      P0106     S079         2       12.94      0.00
1       2024-08-03      P0037     S017         5        3.66      0.00
2       2024-05-12      P0196     S015         4        4.54      0.00
3       2023-01-31      P0030     S011         5       13.91      0.00
4       2023-02-12      P0004     S039         2       12.70      0.15
...            ...        ...      ...       ...         ...       ...
999995  2023-11-25      P0064     S002         1       14.23      0.15
999996  2024-06-23      P0102     S006         2       13.62      0.00
999997  2024-09-04      P0030     S040         5        5.94      0.15
999998  2024-10-22      P0140     S025         1        9.84      0.00
999999  2024-04-02      P0120     S028         4        8.41      0.00

        revenue   cost  profit
0         25.88  16.25    9.63
1         18.30   9.31    8.99
2         18.16  10.48    7.68
3         69.55  39.24   30.31
4         21.59  13.58    8.01
...         ...    ...     ...
999995    12.10   7.26    4.84
999996    27.24  13.94   13.30
999997    25.25  15.38    9.86
999998     9.84   6.18    3.66
999999    33.64  22.65   10.99

[1000000 rows x 15 columns]

In [ ]:
mcsa.groupby('age')['profit'].sum()

age
18    194390.00
19    202201.93
20    183624.93
21    200029.56
22    196535.37
23    198467.05
24    188905.10
25    188475.48
26    188689.96
27    185317.33
28    186819.42
29    196331.39
30    180226.78
31    191744.00
32    189763.18
33    187591.80
34    188960.61
35    199356.49
36    200280.91
37    184010.44
38    201219.28
39    191104.82
40    201406.33
41    174924.01
42    184995.03
43    193764.65
44    192756.90
45    197695.35
46    199357.63
47    195634.51
48    194950.32
49    186874.12
50    193392.80
51    182500.53
52    190358.14
53    184691.29
54    197649.71
55    185318.99
56    197279.58
57    199317.49
58    197018.21
59    185632.01
60    188031.22
61    189479.01
62    191229.82
63    209923.19
64    197518.14
65    197832.24
66    193099.39
67    193237.13
68    191286.39
69    190463.15
70    192901.52
Name: profit, dtype: float64

In [ ]:
customers.replace("Male","M")

      customer_id  age  gender  loyalty_member   join_date
0         C000001   40       M               1  2025-05-21
1         C000002   47       M               0  2021-12-26
2         C000003   58  Female               1  2022-09-13
3         C000004   25  Female               0  2025-02-27
4         C000005   43       M               0  2023-08-31
...           ...  ...     ...             ...         ...
49995     C049996   30  Female               1  2022-11-21
49996     C049997   24  Female               0  2022-08-30
49997     C049998   53       M               0  2024-09-22
49998     C049999   31  Female               1  2025-08-23
49999     C050000   39  Female               1  2023-12-02

[50000 rows x 5 columns]

In [ ]:
customers=customers['age'].astype(float)

In [ ]:
print(customers)

0        40.0
1        47.0
2        58.0
3        25.0
4        43.0
         ...
49995    30.0
49996    24.0
49997    53.0
49998    31.0
49999    39.0
Name: age, Length: 50000, dtype: float64

In [ ]:
products['brand'].unique()

array(['Mars', 'Cadbury', 'Hershey', 'Ferrero', 'Godiva', 'Lindt'],
      dtype=object)

In [ ]:
products.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Length: 200, dtype: bool

In [ ]:
products[products.duplicated()]

Empty DataFrame
Columns: [product_id, product_name, brand, category, cocoa_percent, weight_g]
Index: []